name: each_job
description: "HH vacancies stats"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # text field with suggestions
  flutter_typeahead: ^5.2.0
  # fuzzy search
  fuzzywuzzy: ^1.2.0
  # charts
  fl_chart: ^0.69.0
  # state manager
  flutter_bloc: ^8.1.6
  # json serializing
  json_annotation: ^4.9.0
  # models
  freezed_annotation: ^2.4.4
  # launch urls
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3
  # glowing text
  flutter_glow: ^0.3.0
  # rest client
  retrofit: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # models
  freezed: ^2.5.2
  # json serializing
  json_serializable: ^6.8.0
  # code generation
  build_runner: ^2.4.11
  # rest client
  retrofit_generator: '>=8.0.0 <10.0.0'
  # app icon
  flutter_launcher_icons: ^0.14.3
  # splash screen
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/splash.png"
  android: true
  ios: true
  web: true
  android_12:
    image: "assets/splash/splash.png"
    color: "#FFFFFF"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/splash/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
